/**
 * Business Archetypes Seed Data
 * 
 * 12 common business archetypes with processes, KPIs, starter docs, and risk checklists.
 * Used by the Setup Wizard to guide users through business formation.
 */

import type { IBusinessArchetype } from '../db/models/business-archetype.model.js';

type ArchetypeSeedData = Omit<IBusinessArchetype, '_id' | 'createdAt' | 'updatedAt' | keyof Document>;

export const archetypesSeed: ArchetypeSeedData[] = [
  // 1. Professional Services
  {
    key: 'professional-services',
    name: 'Professional Services',
    description: 'Consulting, legal, accounting, engineering, or other professional expertise-based businesses.',
    icon: 'Briefcase',
    tags: ['consulting', 'b2b', 'service', 'expertise', 'professional'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['Management Consulting', 'Law Firm', 'CPA Firm', 'Engineering Consultancy', 'IT Consulting'],
    commonProcesses: [
      { name: 'Client Engagement', description: 'Onboarding new clients and scoping projects', category: 'operations', priority: 5 },
      { name: 'Service Delivery', description: 'Executing client work and deliverables', category: 'operations', priority: 5 },
      { name: 'Invoicing and Collections', description: 'Billing clients and managing accounts receivable', category: 'finance', priority: 4 },
      { name: 'Business Development', description: 'Generating leads and proposals', category: 'marketing', priority: 4 },
      { name: 'Quality Assurance', description: 'Reviewing deliverables before client submission', category: 'operations', priority: 3 },
    ],
    defaultKPIs: [
      { name: 'Billable Utilization', description: 'Percentage of available hours that are billable', formula: '(Billable Hours / Available Hours) * 100', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Revenue per Employee', description: 'Total revenue divided by number of employees', formula: 'Total Revenue / Employee Count', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Client Retention Rate', description: 'Percentage of clients retained year over year', formula: '(Retained Clients / Total Clients) * 100', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'quarterly' },
      { name: 'Average Project Value', description: 'Mean revenue per project', formula: 'Total Project Revenue / Number of Projects', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Days Sales Outstanding', description: 'Average days to collect payment', formula: '(Accounts Receivable / Revenue) * Days', unit: 'days', targetDirection: 'decrease', category: 'finance', frequency: 'monthly' },
      { name: 'Net Promoter Score', description: 'Client satisfaction and likelihood to recommend', unit: 'score', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Proposal Win Rate', description: 'Percentage of proposals that convert to projects', formula: '(Won Proposals / Total Proposals) * 100', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Gross Margin', description: 'Revenue minus direct costs as percentage', formula: '(Revenue - Direct Costs) / Revenue * 100', unit: '%', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
    ],
    starterDocs: [
      { name: 'Master Services Agreement', description: 'Standard contract template for client engagements', category: 'legal', required: true, legalReview: true },
      { name: 'Statement of Work Template', description: 'Project scope and deliverables template', category: 'operations', required: true, legalReview: false },
      { name: 'Non-Disclosure Agreement', description: 'Confidentiality agreement for client information', category: 'legal', required: true, legalReview: true },
      { name: 'Invoice Template', description: 'Standard invoice format', category: 'finance', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your professional services entity' },
      { templateKey: 'client-onboarding', name: 'Client Onboarding', description: 'Standard process for new client setup', triggerEvent: 'new_client' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Professional licensing requirements verified for your state', severity: 'critical', mitigation: 'Research state licensing board requirements' },
      { category: 'insurance', item: 'Professional liability (E&O) insurance obtained', severity: 'high', mitigation: 'Contact insurance broker for E&O coverage' },
      { category: 'legal', item: 'Client contract templates reviewed by attorney', severity: 'high', mitigation: 'Engage business attorney for contract review' },
      { category: 'financial', item: 'Trust account setup for client funds (if applicable)', severity: 'medium', mitigation: 'Open separate trust account at bank' },
    ],
    commonLicenses: ['Professional License (varies by field)', 'Business License'],
    insuranceTypes: ['Professional Liability (E&O)', 'General Liability', 'Cyber Liability'],
    isActive: true,
    displayOrder: 1,
  },

  // 2. Home Services
  {
    key: 'home-services',
    name: 'Home Services',
    description: 'Residential service businesses including cleaning, landscaping, handyman, and maintenance.',
    icon: 'Home',
    tags: ['residential', 'service', 'local', 'hands-on', 'maintenance'],
    recommendedEntityTypes: ['llc', 'sole_proprietorship'],
    industryExamples: ['House Cleaning', 'Landscaping', 'Handyman Services', 'Pool Maintenance', 'Pest Control'],
    commonProcesses: [
      { name: 'Service Scheduling', description: 'Booking and managing service appointments', category: 'operations', priority: 5 },
      { name: 'Service Delivery', description: 'Performing the actual service at customer location', category: 'operations', priority: 5 },
      { name: 'Customer Communication', description: 'Confirmations, reminders, and follow-ups', category: 'customer_service', priority: 4 },
      { name: 'Equipment and Supply Management', description: 'Maintaining tools and restocking supplies', category: 'operations', priority: 3 },
      { name: 'Billing and Payments', description: 'Invoicing customers and collecting payments', category: 'finance', priority: 4 },
    ],
    defaultKPIs: [
      { name: 'Jobs Completed per Day', description: 'Number of service calls completed daily', unit: 'jobs', targetDirection: 'increase', category: 'operations', frequency: 'daily' },
      { name: 'Customer Retention Rate', description: 'Percentage of repeat customers', formula: '(Repeat Customers / Total Customers) * 100', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Average Job Value', description: 'Mean revenue per service call', formula: 'Total Revenue / Number of Jobs', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'weekly' },
      { name: 'On-Time Arrival Rate', description: 'Percentage of appointments arrived on time', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Customer Satisfaction Score', description: 'Average rating from customer feedback', unit: 'score', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Revenue per Route', description: 'Revenue generated per service route/area', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'weekly' },
      { name: 'Employee Productivity', description: 'Jobs completed per employee per day', unit: 'jobs', targetDirection: 'increase', category: 'operations', frequency: 'daily' },
      { name: 'Referral Rate', description: 'Percentage of new customers from referrals', unit: '%', targetDirection: 'increase', category: 'marketing', frequency: 'monthly' },
    ],
    starterDocs: [
      { name: 'Service Agreement', description: 'Terms of service for residential customers', category: 'legal', required: true, legalReview: true },
      { name: 'Service Checklist', description: 'Quality assurance checklist for each service type', category: 'operations', required: true, legalReview: false },
      { name: 'Customer Intake Form', description: 'Information collection for new customers', category: 'operations', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your home services business' },
    ],
    riskChecklist: [
      { category: 'insurance', item: 'General liability insurance obtained', severity: 'critical', mitigation: 'Contact insurance broker for GL coverage' },
      { category: 'compliance', item: 'Home improvement contractor license (if required)', severity: 'high', mitigation: 'Check state requirements for contractor licensing' },
      { category: 'insurance', item: 'Workers compensation (if employees)', severity: 'high', mitigation: 'Obtain workers comp before hiring' },
      { category: 'financial', item: 'Vehicle insurance for business use', severity: 'medium', mitigation: 'Update auto policy or get commercial vehicle insurance' },
    ],
    commonLicenses: ['Business License', 'Home Improvement Contractor License (varies by state)'],
    insuranceTypes: ['General Liability', 'Workers Compensation', 'Commercial Auto'],
    isActive: true,
    displayOrder: 2,
  },

  // 3. E-commerce
  {
    key: 'ecommerce',
    name: 'E-commerce',
    description: 'Online retail businesses selling products through websites or marketplaces.',
    icon: 'ShoppingCart',
    tags: ['online', 'retail', 'digital', 'products', 'marketplace'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['Shopify Store', 'Amazon Seller', 'Etsy Shop', 'Direct-to-Consumer Brand', 'Dropshipping'],
    commonProcesses: [
      { name: 'Order Fulfillment', description: 'Processing and shipping customer orders', category: 'operations', priority: 5 },
      { name: 'Inventory Management', description: 'Tracking stock levels and reordering', category: 'operations', priority: 5 },
      { name: 'Customer Service', description: 'Handling inquiries, returns, and support', category: 'customer_service', priority: 4 },
      { name: 'Marketing and Acquisition', description: 'Driving traffic and converting visitors', category: 'marketing', priority: 4 },
      { name: 'Product Sourcing', description: 'Finding and evaluating suppliers', category: 'operations', priority: 3 },
    ],
    defaultKPIs: [
      { name: 'Conversion Rate', description: 'Percentage of visitors who purchase', formula: '(Orders / Visitors) * 100', unit: '%', targetDirection: 'increase', category: 'marketing', frequency: 'daily' },
      { name: 'Average Order Value', description: 'Mean revenue per order', formula: 'Total Revenue / Number of Orders', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'daily' },
      { name: 'Customer Acquisition Cost', description: 'Marketing spend per new customer', formula: 'Marketing Spend / New Customers', unit: '$', targetDirection: 'decrease', category: 'marketing', frequency: 'weekly' },
      { name: 'Return Rate', description: 'Percentage of orders returned', formula: '(Returns / Orders) * 100', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'weekly' },
      { name: 'Inventory Turnover', description: 'How often inventory sells through', formula: 'COGS / Average Inventory', unit: 'x', targetDirection: 'increase', category: 'operations', frequency: 'monthly' },
      { name: 'Customer Lifetime Value', description: 'Total revenue expected from a customer', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'quarterly' },
      { name: 'Cart Abandonment Rate', description: 'Percentage of carts not completed', unit: '%', targetDirection: 'decrease', category: 'marketing', frequency: 'daily' },
      { name: 'Gross Margin', description: 'Revenue minus product costs', formula: '(Revenue - COGS) / Revenue * 100', unit: '%', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
    ],
    starterDocs: [
      { name: 'Terms of Service', description: 'Website terms and conditions', category: 'legal', required: true, legalReview: true },
      { name: 'Privacy Policy', description: 'Data collection and usage policy', category: 'legal', required: true, legalReview: true },
      { name: 'Return Policy', description: 'Product return and refund terms', category: 'operations', required: true, legalReview: false },
      { name: 'Shipping Policy', description: 'Shipping methods and delivery terms', category: 'operations', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your e-commerce business' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Sales tax nexus and collection setup', severity: 'critical', mitigation: 'Register for sales tax in required states' },
      { category: 'legal', item: 'Privacy policy and terms of service published', severity: 'high', mitigation: 'Have attorney review policies' },
      { category: 'financial', item: 'Payment processor and merchant account setup', severity: 'high', mitigation: 'Apply for Stripe/PayPal business account' },
      { category: 'compliance', item: 'Product safety and labeling requirements met', severity: 'medium', mitigation: 'Research CPSC requirements for your products' },
    ],
    commonLicenses: ['Business License', 'Sales Tax Permit', 'Reseller Certificate'],
    insuranceTypes: ['General Liability', 'Product Liability', 'Cyber Liability'],
    isActive: true,
    displayOrder: 3,
  },

  // 4. Retail Store
  {
    key: 'retail-store',
    name: 'Retail Store',
    description: 'Brick-and-mortar retail businesses with a physical storefront.',
    icon: 'Store',
    tags: ['physical', 'storefront', 'local', 'products', 'retail'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['Boutique Shop', 'Convenience Store', 'Gift Shop', 'Specialty Foods', 'Hardware Store'],
    commonProcesses: [
      { name: 'Sales and Checkout', description: 'Processing customer transactions', category: 'operations', priority: 5 },
      { name: 'Inventory Management', description: 'Stock tracking and replenishment', category: 'operations', priority: 5 },
      { name: 'Visual Merchandising', description: 'Store layout and product display', category: 'marketing', priority: 3 },
      { name: 'Staff Scheduling', description: 'Managing employee shifts and coverage', category: 'hr', priority: 4 },
      { name: 'Vendor Relations', description: 'Managing supplier relationships', category: 'operations', priority: 3 },
    ],
    defaultKPIs: [
      { name: 'Sales per Square Foot', description: 'Revenue relative to store size', formula: 'Total Sales / Square Footage', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Average Transaction Value', description: 'Mean revenue per customer', formula: 'Total Sales / Number of Transactions', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'daily' },
      { name: 'Foot Traffic', description: 'Number of customers entering store', unit: 'visitors', targetDirection: 'increase', category: 'marketing', frequency: 'daily' },
      { name: 'Conversion Rate', description: 'Visitors who make a purchase', formula: '(Transactions / Visitors) * 100', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'daily' },
      { name: 'Inventory Shrinkage', description: 'Lost inventory as percentage of sales', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'monthly' },
      { name: 'Gross Margin Return on Investment', description: 'Gross margin relative to inventory investment', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Employee Sales per Hour', description: 'Sales generated per labor hour', formula: 'Total Sales / Labor Hours', unit: '$', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Customer Return Rate', description: 'Percentage of repeat customers', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
    ],
    starterDocs: [
      { name: 'Lease Agreement Review Checklist', description: 'Key terms to review in commercial lease', category: 'legal', required: true, legalReview: true },
      { name: 'Employee Handbook', description: 'Policies and procedures for staff', category: 'hr', required: false, legalReview: true },
      { name: 'Point of Sale Procedures', description: 'Checkout and cash handling procedures', category: 'operations', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your retail business' },
    ],
    riskChecklist: [
      { category: 'legal', item: 'Commercial lease reviewed and signed', severity: 'critical', mitigation: 'Have attorney review lease before signing' },
      { category: 'compliance', item: 'Sales tax permit obtained', severity: 'critical', mitigation: 'Register with state revenue department' },
      { category: 'insurance', item: 'General liability and property insurance', severity: 'high', mitigation: 'Contact insurance broker' },
      { category: 'compliance', item: 'Zoning approval for retail use', severity: 'high', mitigation: 'Verify zoning with local planning department' },
    ],
    commonLicenses: ['Business License', 'Sales Tax Permit', 'Certificate of Occupancy', 'Sign Permit'],
    insuranceTypes: ['General Liability', 'Property Insurance', 'Workers Compensation', 'Business Interruption'],
    isActive: true,
    displayOrder: 4,
  },

  // 5. Food Business
  {
    key: 'food-business',
    name: 'Food Business',
    description: 'Food service businesses including restaurants, food trucks, catering, and packaged foods.',
    icon: 'Utensils',
    tags: ['food', 'hospitality', 'service', 'restaurant', 'culinary'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['Restaurant', 'Food Truck', 'Catering Company', 'Bakery', 'Packaged Food Producer'],
    commonProcesses: [
      { name: 'Food Preparation', description: 'Cooking and assembling food items', category: 'operations', priority: 5 },
      { name: 'Inventory and Ordering', description: 'Managing food supplies and vendor orders', category: 'operations', priority: 5 },
      { name: 'Food Safety Compliance', description: 'Maintaining health code standards', category: 'compliance', priority: 5 },
      { name: 'Customer Service', description: 'Taking orders and serving customers', category: 'customer_service', priority: 4 },
      { name: 'Staff Management', description: 'Scheduling and training kitchen/service staff', category: 'hr', priority: 4 },
    ],
    defaultKPIs: [
      { name: 'Food Cost Percentage', description: 'Food cost as percentage of food sales', formula: '(Food Cost / Food Sales) * 100', unit: '%', targetDirection: 'decrease', category: 'finance', frequency: 'weekly' },
      { name: 'Labor Cost Percentage', description: 'Labor cost as percentage of sales', formula: '(Labor Cost / Sales) * 100', unit: '%', targetDirection: 'decrease', category: 'finance', frequency: 'weekly' },
      { name: 'Table Turnover Rate', description: 'How many times tables turn per service', unit: 'turns', targetDirection: 'increase', category: 'operations', frequency: 'daily' },
      { name: 'Average Check Size', description: 'Mean revenue per customer', formula: 'Total Sales / Number of Customers', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'daily' },
      { name: 'Health Inspection Score', description: 'Latest health department score', unit: 'score', targetDirection: 'increase', category: 'compliance', frequency: 'quarterly' },
      { name: 'Food Waste Percentage', description: 'Waste as percentage of food purchased', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'weekly' },
      { name: 'Customer Satisfaction', description: 'Average rating from reviews', unit: 'stars', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Revenue per Labor Hour', description: 'Sales generated per staff hour worked', formula: 'Total Sales / Labor Hours', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'daily' },
    ],
    starterDocs: [
      { name: 'Food Safety Plan', description: 'HACCP-based food safety procedures', category: 'compliance', required: true, legalReview: false },
      { name: 'Menu with Allergen Information', description: 'Menu items with allergen declarations', category: 'compliance', required: true, legalReview: false },
      { name: 'Employee Food Handler Training Log', description: 'Tracking food safety certifications', category: 'compliance', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your food business' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Food service license/permit obtained', severity: 'critical', mitigation: 'Apply with local health department' },
      { category: 'compliance', item: 'Health department inspection passed', severity: 'critical', mitigation: 'Schedule pre-opening inspection' },
      { category: 'compliance', item: 'Food handler certifications for all staff', severity: 'high', mitigation: 'Enroll staff in ServSafe or equivalent' },
      { category: 'insurance', item: 'Product liability insurance for food products', severity: 'high', mitigation: 'Obtain food-specific liability coverage' },
    ],
    commonLicenses: ['Business License', 'Food Service License', 'Health Permit', 'Liquor License (if applicable)'],
    commonPermits: ['Food Handler Permits', 'Fire Department Permit', 'Sign Permit'],
    insuranceTypes: ['General Liability', 'Product Liability', 'Workers Compensation', 'Liquor Liability'],
    isActive: true,
    displayOrder: 5,
  },

  // 6. Personal Care/Beauty
  {
    key: 'personal-care',
    name: 'Personal Care and Beauty',
    description: 'Beauty salons, barbershops, spas, and personal care service businesses.',
    icon: 'Scissors',
    tags: ['beauty', 'personal care', 'service', 'wellness', 'salon'],
    recommendedEntityTypes: ['llc', 'sole_proprietorship'],
    industryExamples: ['Hair Salon', 'Barbershop', 'Nail Salon', 'Day Spa', 'Massage Therapy'],
    commonProcesses: [
      { name: 'Appointment Booking', description: 'Scheduling client appointments', category: 'operations', priority: 5 },
      { name: 'Service Delivery', description: 'Performing beauty/care services', category: 'operations', priority: 5 },
      { name: 'Client Consultation', description: 'Understanding client needs and preferences', category: 'customer_service', priority: 4 },
      { name: 'Retail Sales', description: 'Selling products to complement services', category: 'sales', priority: 3 },
      { name: 'Sanitation and Compliance', description: 'Maintaining hygiene standards', category: 'compliance', priority: 5 },
    ],
    defaultKPIs: [
      { name: 'Client Retention Rate', description: 'Percentage of returning clients', formula: '(Repeat Clients / Total Clients) * 100', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Revenue per Service Hour', description: 'Revenue generated per hour of service', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'weekly' },
      { name: 'Average Ticket Value', description: 'Mean spend per client visit', formula: 'Total Revenue / Number of Visits', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'weekly' },
      { name: 'Booking Rate', description: 'Percentage of available slots booked', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Retail to Service Ratio', description: 'Product sales as percentage of total', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'No-Show Rate', description: 'Percentage of missed appointments', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'weekly' },
      { name: 'New Client Acquisition', description: 'Number of new clients per month', unit: 'clients', targetDirection: 'increase', category: 'marketing', frequency: 'monthly' },
      { name: 'Online Review Rating', description: 'Average rating across platforms', unit: 'stars', targetDirection: 'increase', category: 'marketing', frequency: 'monthly' },
    ],
    starterDocs: [
      { name: 'Client Intake Form', description: 'Health and preference questionnaire', category: 'operations', required: true, legalReview: false },
      { name: 'Service Menu', description: 'List of services and pricing', category: 'operations', required: true, legalReview: false },
      { name: 'Consent and Waiver Form', description: 'Client consent for services', category: 'legal', required: true, legalReview: true },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your personal care business' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Cosmetology/barber license obtained', severity: 'critical', mitigation: 'Apply through state licensing board' },
      { category: 'compliance', item: 'Establishment license/permit obtained', severity: 'critical', mitigation: 'Register with state board and local health' },
      { category: 'insurance', item: 'Professional liability insurance', severity: 'high', mitigation: 'Obtain salon/spa specific coverage' },
      { category: 'compliance', item: 'Sanitation standards and inspection passed', severity: 'high', mitigation: 'Review state sanitation requirements' },
    ],
    commonLicenses: ['Cosmetology License', 'Establishment License', 'Business License'],
    insuranceTypes: ['Professional Liability', 'General Liability', 'Property Insurance'],
    isActive: true,
    displayOrder: 6,
  },

  // 7. Fitness/Coaching
  {
    key: 'fitness-coaching',
    name: 'Fitness and Coaching',
    description: 'Personal training, fitness studios, life coaching, and wellness coaching businesses.',
    icon: 'Dumbbell',
    tags: ['fitness', 'wellness', 'coaching', 'training', 'health'],
    recommendedEntityTypes: ['llc', 'sole_proprietorship'],
    industryExamples: ['Personal Training', 'Yoga Studio', 'CrossFit Gym', 'Life Coaching', 'Nutrition Coaching'],
    commonProcesses: [
      { name: 'Client Assessment', description: 'Evaluating client fitness/goals', category: 'operations', priority: 5 },
      { name: 'Program Design', description: 'Creating customized plans', category: 'operations', priority: 5 },
      { name: 'Session Delivery', description: 'Conducting training/coaching sessions', category: 'operations', priority: 5 },
      { name: 'Progress Tracking', description: 'Monitoring client results', category: 'operations', priority: 4 },
      { name: 'Client Retention', description: 'Maintaining long-term relationships', category: 'customer_service', priority: 4 },
    ],
    defaultKPIs: [
      { name: 'Client Retention Rate', description: 'Percentage of clients who continue', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Sessions Delivered per Week', description: 'Number of sessions conducted', unit: 'sessions', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Revenue per Client', description: 'Average revenue per active client', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Session Utilization', description: 'Booked sessions vs available slots', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Client Goal Achievement', description: 'Percentage meeting their goals', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Referral Rate', description: 'New clients from referrals', unit: '%', targetDirection: 'increase', category: 'marketing', frequency: 'monthly' },
      { name: 'Package Renewal Rate', description: 'Clients renewing packages', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'No-Show Rate', description: 'Missed sessions percentage', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'weekly' },
    ],
    starterDocs: [
      { name: 'Liability Waiver', description: 'Release of liability for physical activities', category: 'legal', required: true, legalReview: true },
      { name: 'Health Questionnaire', description: 'PAR-Q or similar health screening', category: 'operations', required: true, legalReview: false },
      { name: 'Client Agreement', description: 'Terms of service and cancellation policy', category: 'legal', required: true, legalReview: true },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your fitness business' },
    ],
    riskChecklist: [
      { category: 'insurance', item: 'Professional liability insurance obtained', severity: 'critical', mitigation: 'Get fitness-specific liability coverage' },
      { category: 'legal', item: 'Liability waivers in place for all clients', severity: 'critical', mitigation: 'Have attorney review waiver forms' },
      { category: 'compliance', item: 'Professional certifications current', severity: 'high', mitigation: 'Maintain CPR/AED and fitness certifications' },
      { category: 'compliance', item: 'Facility safety requirements met (if applicable)', severity: 'medium', mitigation: 'Review local gym/studio requirements' },
    ],
    commonLicenses: ['Business License', 'Professional Certifications'],
    insuranceTypes: ['Professional Liability', 'General Liability', 'Property Insurance'],
    isActive: true,
    displayOrder: 7,
  },

  // 8. Real Estate Services
  {
    key: 'real-estate',
    name: 'Real Estate Services',
    description: 'Real estate brokerage, property management, and related services.',
    icon: 'Building',
    tags: ['real estate', 'property', 'brokerage', 'management', 'housing'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['Real Estate Brokerage', 'Property Management', 'Real Estate Investment', 'Leasing Agency'],
    commonProcesses: [
      { name: 'Lead Generation', description: 'Finding potential clients', category: 'marketing', priority: 5 },
      { name: 'Property Marketing', description: 'Listing and promoting properties', category: 'marketing', priority: 5 },
      { name: 'Transaction Management', description: 'Managing deals from contract to close', category: 'operations', priority: 5 },
      { name: 'Client Communication', description: 'Keeping buyers/sellers informed', category: 'customer_service', priority: 4 },
      { name: 'Compliance and Documentation', description: 'Maintaining required records', category: 'compliance', priority: 4 },
    ],
    defaultKPIs: [
      { name: 'Closed Transactions', description: 'Number of deals closed', unit: 'deals', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Gross Commission Income', description: 'Total commissions earned', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Average Days on Market', description: 'Mean time to sell listings', unit: 'days', targetDirection: 'decrease', category: 'operations', frequency: 'monthly' },
      { name: 'List to Sale Price Ratio', description: 'Final price vs listing price', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Lead Conversion Rate', description: 'Leads that become clients', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Client Satisfaction Score', description: 'Post-transaction ratings', unit: 'score', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Listings Inventory', description: 'Number of active listings', unit: 'listings', targetDirection: 'increase', category: 'sales', frequency: 'weekly' },
      { name: 'Referral Rate', description: 'Business from past client referrals', unit: '%', targetDirection: 'increase', category: 'marketing', frequency: 'quarterly' },
    ],
    starterDocs: [
      { name: 'Listing Agreement Template', description: 'Seller representation contract', category: 'legal', required: true, legalReview: true },
      { name: 'Buyer Representation Agreement', description: 'Buyer agency contract', category: 'legal', required: true, legalReview: true },
      { name: 'Transaction Checklist', description: 'Steps from contract to closing', category: 'operations', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your real estate business' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Real estate license obtained and active', severity: 'critical', mitigation: 'Complete licensing requirements' },
      { category: 'compliance', item: 'Brokerage affiliation established', severity: 'critical', mitigation: 'Join a brokerage or obtain broker license' },
      { category: 'insurance', item: 'Errors and omissions insurance', severity: 'high', mitigation: 'Obtain E&O coverage' },
      { category: 'compliance', item: 'Fair housing training completed', severity: 'high', mitigation: 'Complete fair housing certification' },
    ],
    commonLicenses: ['Real Estate License', 'Broker License', 'Business License'],
    insuranceTypes: ['Errors & Omissions', 'General Liability'],
    isActive: true,
    displayOrder: 8,
  },

  // 9. Construction/Trades
  {
    key: 'construction-trades',
    name: 'Construction and Trades',
    description: 'General contracting, specialty trades, and construction services.',
    icon: 'Hammer',
    tags: ['construction', 'trades', 'contractor', 'building', 'skilled'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['General Contractor', 'Electrician', 'Plumber', 'HVAC Contractor', 'Roofing Company'],
    commonProcesses: [
      { name: 'Estimating and Bidding', description: 'Preparing project estimates and bids', category: 'sales', priority: 5 },
      { name: 'Project Management', description: 'Planning and executing construction projects', category: 'operations', priority: 5 },
      { name: 'Subcontractor Management', description: 'Coordinating specialty trades', category: 'operations', priority: 4 },
      { name: 'Permit and Inspection', description: 'Managing permits and inspections', category: 'compliance', priority: 5 },
      { name: 'Change Order Management', description: 'Handling scope changes', category: 'operations', priority: 4 },
    ],
    defaultKPIs: [
      { name: 'Gross Profit Margin', description: 'Profit after direct costs', formula: '(Revenue - Direct Costs) / Revenue * 100', unit: '%', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Bid Win Rate', description: 'Percentage of bids won', formula: '(Won Bids / Total Bids) * 100', unit: '%', targetDirection: 'increase', category: 'sales', frequency: 'monthly' },
      { name: 'Project On-Time Rate', description: 'Projects completed on schedule', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Safety Incident Rate', description: 'Incidents per work hours', unit: 'rate', targetDirection: 'decrease', category: 'compliance', frequency: 'monthly' },
      { name: 'Backlog Value', description: 'Contracted work not yet completed', unit: '$', targetDirection: 'maintain', category: 'finance', frequency: 'monthly' },
      { name: 'Change Order Percentage', description: 'Change orders as percent of contract', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'monthly' },
      { name: 'Customer Satisfaction', description: 'Post-project satisfaction scores', unit: 'score', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Warranty Callback Rate', description: 'Callbacks within warranty period', unit: '%', targetDirection: 'decrease', category: 'operations', frequency: 'quarterly' },
    ],
    starterDocs: [
      { name: 'Construction Contract Template', description: 'Standard construction agreement', category: 'legal', required: true, legalReview: true },
      { name: 'Change Order Form', description: 'Scope change documentation', category: 'operations', required: true, legalReview: false },
      { name: 'Safety Plan', description: 'Job site safety procedures', category: 'compliance', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your construction business' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Contractor license obtained', severity: 'critical', mitigation: 'Apply through state licensing board' },
      { category: 'insurance', item: 'General liability insurance with adequate limits', severity: 'critical', mitigation: 'Work with construction insurance specialist' },
      { category: 'insurance', item: 'Workers compensation insurance', severity: 'critical', mitigation: 'Required before hiring employees' },
      { category: 'financial', item: 'Contractor bond obtained (if required)', severity: 'high', mitigation: 'Apply for surety bond' },
    ],
    commonLicenses: ['Contractor License', 'Trade-Specific License', 'Business License'],
    insuranceTypes: ['General Liability', 'Workers Compensation', 'Builders Risk', 'Commercial Auto', 'Umbrella'],
    isActive: true,
    displayOrder: 9,
  },

  // 10. Transportation/Delivery
  {
    key: 'transportation',
    name: 'Transportation and Delivery',
    description: 'Delivery services, courier, trucking, and transportation businesses.',
    icon: 'Truck',
    tags: ['transportation', 'delivery', 'logistics', 'courier', 'trucking'],
    recommendedEntityTypes: ['llc', 'corporation'],
    industryExamples: ['Local Delivery Service', 'Courier Service', 'Trucking Company', 'Moving Company', 'Last-Mile Delivery'],
    commonProcesses: [
      { name: 'Order Dispatch', description: 'Assigning and routing deliveries', category: 'operations', priority: 5 },
      { name: 'Route Optimization', description: 'Planning efficient delivery routes', category: 'operations', priority: 4 },
      { name: 'Fleet Management', description: 'Maintaining vehicles and equipment', category: 'operations', priority: 4 },
      { name: 'Driver Management', description: 'Scheduling and tracking drivers', category: 'hr', priority: 4 },
      { name: 'Customer Communication', description: 'Providing delivery updates', category: 'customer_service', priority: 3 },
    ],
    defaultKPIs: [
      { name: 'On-Time Delivery Rate', description: 'Deliveries made within window', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'daily' },
      { name: 'Cost per Delivery', description: 'Average cost to complete delivery', unit: '$', targetDirection: 'decrease', category: 'finance', frequency: 'weekly' },
      { name: 'Revenue per Mile', description: 'Revenue generated per mile driven', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'weekly' },
      { name: 'Vehicle Utilization', description: 'Time vehicles are in productive use', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Delivery Accuracy', description: 'Deliveries without errors', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'daily' },
      { name: 'Fuel Efficiency', description: 'Miles per gallon across fleet', unit: 'mpg', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Driver Safety Score', description: 'Safety metrics for drivers', unit: 'score', targetDirection: 'increase', category: 'compliance', frequency: 'weekly' },
      { name: 'Customer Satisfaction', description: 'Delivery experience ratings', unit: 'stars', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
    ],
    starterDocs: [
      { name: 'Service Agreement', description: 'Terms for delivery services', category: 'legal', required: true, legalReview: true },
      { name: 'Driver Handbook', description: 'Policies for drivers', category: 'hr', required: true, legalReview: false },
      { name: 'Vehicle Inspection Checklist', description: 'Daily vehicle inspection form', category: 'compliance', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your transportation business' },
    ],
    riskChecklist: [
      { category: 'insurance', item: 'Commercial auto insurance obtained', severity: 'critical', mitigation: 'Work with commercial auto insurance specialist' },
      { category: 'compliance', item: 'DOT registration (if applicable)', severity: 'high', mitigation: 'Register with DOT for interstate commerce' },
      { category: 'compliance', item: 'Driver qualification files maintained', severity: 'high', mitigation: 'Establish driver file requirements' },
      { category: 'insurance', item: 'Cargo insurance for goods transported', severity: 'medium', mitigation: 'Add cargo coverage to policy' },
    ],
    commonLicenses: ['Business License', 'Motor Carrier Authority', 'DOT Number'],
    insuranceTypes: ['Commercial Auto', 'Cargo Insurance', 'General Liability', 'Workers Compensation'],
    isActive: true,
    displayOrder: 10,
  },

  // 11. Childcare
  {
    key: 'childcare',
    name: 'Childcare',
    description: 'Daycare centers, in-home childcare, and early education businesses.',
    icon: 'Baby',
    tags: ['childcare', 'daycare', 'education', 'children', 'early learning'],
    recommendedEntityTypes: ['llc', 'corporation', 'nonprofit'],
    industryExamples: ['Daycare Center', 'In-Home Childcare', 'Preschool', 'After-School Program', 'Nanny Agency'],
    commonProcesses: [
      { name: 'Child Enrollment', description: 'Registering and onboarding children', category: 'operations', priority: 5 },
      { name: 'Daily Care Delivery', description: 'Providing safe, nurturing care', category: 'operations', priority: 5 },
      { name: 'Parent Communication', description: 'Updates and engagement with families', category: 'customer_service', priority: 4 },
      { name: 'Staff Management', description: 'Hiring, training, and scheduling caregivers', category: 'hr', priority: 5 },
      { name: 'Compliance and Licensing', description: 'Maintaining licensing requirements', category: 'compliance', priority: 5 },
    ],
    defaultKPIs: [
      { name: 'Enrollment Rate', description: 'Filled spots vs capacity', formula: '(Enrolled Children / Capacity) * 100', unit: '%', targetDirection: 'increase', category: 'operations', frequency: 'weekly' },
      { name: 'Staff-to-Child Ratio', description: 'Caregivers per child', unit: 'ratio', targetDirection: 'maintain', category: 'compliance', frequency: 'daily' },
      { name: 'Parent Satisfaction', description: 'Family satisfaction scores', unit: 'score', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Staff Retention Rate', description: 'Caregiver retention', unit: '%', targetDirection: 'increase', category: 'hr', frequency: 'quarterly' },
      { name: 'Revenue per Child', description: 'Average revenue per enrolled child', unit: '$', targetDirection: 'increase', category: 'finance', frequency: 'monthly' },
      { name: 'Licensing Compliance Score', description: 'Regulatory compliance rating', unit: '%', targetDirection: 'increase', category: 'compliance', frequency: 'quarterly' },
      { name: 'Incident Rate', description: 'Safety incidents per period', unit: 'incidents', targetDirection: 'decrease', category: 'compliance', frequency: 'monthly' },
      { name: 'Waitlist Size', description: 'Number of children on waitlist', unit: 'children', targetDirection: 'increase', category: 'sales', frequency: 'weekly' },
    ],
    starterDocs: [
      { name: 'Enrollment Agreement', description: 'Family contract and policies', category: 'legal', required: true, legalReview: true },
      { name: 'Child Emergency Information Form', description: 'Emergency contacts and medical info', category: 'compliance', required: true, legalReview: false },
      { name: 'Daily Health Check Form', description: 'Wellness screening documentation', category: 'compliance', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Business Formation', description: 'Form your childcare business' },
    ],
    riskChecklist: [
      { category: 'compliance', item: 'Childcare license obtained', severity: 'critical', mitigation: 'Apply through state licensing agency' },
      { category: 'compliance', item: 'Background checks for all staff', severity: 'critical', mitigation: 'Complete required background screenings' },
      { category: 'compliance', item: 'Staff-to-child ratios documented', severity: 'critical', mitigation: 'Review state ratio requirements' },
      { category: 'insurance', item: 'Childcare liability insurance', severity: 'critical', mitigation: 'Obtain childcare-specific coverage' },
    ],
    commonLicenses: ['Childcare License', 'Business License', 'Health Inspection Certificate'],
    insuranceTypes: ['Professional Liability', 'General Liability', 'Workers Compensation', 'Abuse and Molestation Coverage'],
    isActive: true,
    displayOrder: 11,
  },

  // 12. Nonprofit
  {
    key: 'nonprofit',
    name: 'Nonprofit Organization',
    description: 'Charitable organizations, foundations, and social enterprises.',
    icon: 'Heart',
    tags: ['nonprofit', 'charity', 'foundation', 'social impact', '501c3'],
    recommendedEntityTypes: ['nonprofit', 'corporation'],
    industryExamples: ['Charitable Foundation', 'Community Organization', 'Educational Nonprofit', 'Social Services', 'Arts Organization'],
    commonProcesses: [
      { name: 'Fundraising', description: 'Soliciting donations and grants', category: 'finance', priority: 5 },
      { name: 'Program Delivery', description: 'Executing mission-driven programs', category: 'operations', priority: 5 },
      { name: 'Donor Management', description: 'Cultivating and stewarding donors', category: 'customer_service', priority: 4 },
      { name: 'Grant Management', description: 'Writing, managing, and reporting grants', category: 'finance', priority: 4 },
      { name: 'Board Governance', description: 'Supporting board of directors', category: 'administration', priority: 4 },
    ],
    defaultKPIs: [
      { name: 'Program Expense Ratio', description: 'Program spending vs total expenses', formula: '(Program Expenses / Total Expenses) * 100', unit: '%', targetDirection: 'increase', category: 'finance', frequency: 'quarterly' },
      { name: 'Fundraising Efficiency', description: 'Cost to raise $1', formula: 'Fundraising Costs / Donations Raised', unit: '$', targetDirection: 'decrease', category: 'finance', frequency: 'quarterly' },
      { name: 'Donor Retention Rate', description: 'Donors who give again', unit: '%', targetDirection: 'increase', category: 'finance', frequency: 'yearly' },
      { name: 'Mission Impact Metrics', description: 'Beneficiaries served/outcomes achieved', unit: 'varies', targetDirection: 'increase', category: 'operations', frequency: 'quarterly' },
      { name: 'Grant Success Rate', description: 'Grant applications funded', unit: '%', targetDirection: 'increase', category: 'finance', frequency: 'yearly' },
      { name: 'Volunteer Engagement', description: 'Active volunteers and hours', unit: 'hours', targetDirection: 'increase', category: 'operations', frequency: 'monthly' },
      { name: 'Operating Reserve Ratio', description: 'Months of reserves on hand', unit: 'months', targetDirection: 'increase', category: 'finance', frequency: 'quarterly' },
      { name: 'Board Engagement Score', description: 'Board member participation', unit: '%', targetDirection: 'increase', category: 'administration', frequency: 'quarterly' },
    ],
    starterDocs: [
      { name: 'Bylaws', description: 'Organizational governing document', category: 'legal', required: true, legalReview: true },
      { name: 'Conflict of Interest Policy', description: 'Board and staff COI policy', category: 'compliance', required: true, legalReview: true },
      { name: 'Gift Acceptance Policy', description: 'Guidelines for accepting donations', category: 'finance', required: true, legalReview: false },
    ],
    starterWorkflows: [
      { templateKey: 'business-formation', name: 'Nonprofit Formation', description: 'Form your nonprofit organization' },
    ],
    riskChecklist: [
      { category: 'compliance', item: '501(c)(3) application prepared', severity: 'critical', mitigation: 'Prepare Form 1023 or 1023-EZ' },
      { category: 'compliance', item: 'State charitable registration filed', severity: 'high', mitigation: 'Register in states where soliciting' },
      { category: 'compliance', item: 'Board of directors established', severity: 'high', mitigation: 'Recruit and onboard board members' },
      { category: 'financial', item: 'Fund accounting system established', severity: 'medium', mitigation: 'Set up restricted/unrestricted fund tracking' },
    ],
    commonLicenses: ['State Incorporation', '501(c)(3) Determination Letter', 'Charitable Solicitation Registration'],
    insuranceTypes: ['Directors & Officers', 'General Liability', 'Workers Compensation'],
    isActive: true,
    displayOrder: 12,
  },
];

export default archetypesSeed;
